#!/usr/bin/env python3
"""Regenerate a target's raw byte blobs (asm/header.s and friends) from your ELF.

The parts of an ELF that aren't code or data, such as the ELF header, the
program headers and (for boot_elf) the section-header table at the end, are
captured as byte dumps rather than reconstructed. tools/targets.py lists them
per target (raw_blobs). They're regenerated from YOUR OWN legally obtained ELF,
like the rest of asm/, and never committed.

Emits `.byte` directives rather than `.incbin`: this project's SN Systems
ee-as.exe has no working .incbin (confirmed: "Unknown pseudo-op" plus a bfd
assertion fail in elf32-mips.c), so the bytes are written into the assembly.

    python tools/extract_header.py                    # frontbin: asm/header.s
    python tools/extract_header.py --target boot_elf  # asm/boot_elf/header.s, trailer.s
"""
import hashlib
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import targets  # noqa: E402


def main():
    t = targets.from_argv()
    elf = t.path("elf")
    if not os.path.exists(elf):
        raise SystemExit(f"{t.elf} not found -- supply your own legally-obtained copy")
    data = open(elf, "rb").read()
    sha1 = hashlib.sha1(data).hexdigest()
    if sha1 != t.sha1:
        print(f"WARNING: {t.elf} sha1 {sha1}, expected {t.sha1} (continuing anyway)")
    for name, start, end in t.raw_blobs:
        blob = data[start:end]
        lines = [
            f"/* {name}.s -- raw bytes 0x{start:X}..0x{end:X} of {t.elf}. Auto-generated by",
            " * tools/extract_header.py from your local copy -- do not hand-edit, and do",
            " * not commit this file (it's derived from copyrighted retail data).",
            " *",
            " * Emitted as .byte directives, not .incbin: this project's ee-as.exe",
            " * build has no working .incbin support.",
            " */",
            ".section .data",
            ".align 4",
        ]
        for i in range(0, len(blob), 16):
            lines.append("    .byte " + ", ".join(f"0x{b:02X}" for b in blob[i:i + 16]))
        out = os.path.join(t.path("asm_root"), name + ".s")
        os.makedirs(os.path.dirname(out), exist_ok=True)
        open(out, "w").write("\n".join(lines) + "\n")
        print(f"Wrote {len(blob)} bytes to {os.path.relpath(out, targets.ROOT)}")


if __name__ == "__main__":
    main()
