#!/usr/bin/env python3
"""gen_divs_nops.py: write tools/divs_nops.txt, the `nop` padding retail has in front of each div.s / sqrt.s.

Retail pads most div.s and sqrt.s with 0-3 `nop`s. gcc and both assemblers drop or ignore
them (see docs/wiki/Matching-Patterns.md), so tools/asm_filter.py puts them back as raw
.words, driven by this table: one line per function, one count per div.s/sqrt.s in order.

    func_0037E568 2

Only functions that are still INCLUDE_ASM get a new line (the ones already in C match without
it), and lines already in the file are kept, so a function keeps its padding after it is
decompiled. --all adds every function.
"""
import glob, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(ROOT, "tools"))
import targets  # noqa: E402

INSN = re.compile(r"/\*[^*]*\*/\s+([a-z][a-z0-9.]*)\b")
BRANCH = re.compile(r"^(b|bc1[tf]l?|beq|bne|bgez|bgtz|blez|bltz|beql|bnel|bgezl|bgtzl|blezl|bltzl|bgezal|bltzal|j|jal|jr|jalr)$")
TARGET = re.compile(r"^(div\.s|sqrt\.s)$")


def counts(path):
    prev = []  # mnemonics before the current line, in order
    out = []
    for line in open(path, errors="replace"):
        m = INSN.search(line)
        if not m:
            continue
        mn = m.group(1)
        if TARGET.match(mn):
            n = 0
            i = len(prev) - 1
            while i >= 0 and prev[i] == "nop":
                if i > 0 and BRANCH.match(prev[i - 1]):
                    break  # this nop is a branch delay slot
                n += 1
                i -= 1
            out.append(n)
        prev.append(mn)
    return out


def main():
    t = targets.from_argv(allow_all=True)   # --target boot_elf: that target's sources and table
    OUT = t.path("divs_nops")
    allf = "--all" in sys.argv
    import srcfiles
    text = srcfiles.read_all(ROOT)
    todo = set(re.findall(r'INCLUDE_ASM\("[^"]+",\s*(func_[0-9A-Fa-f]+)\)', text))
    keep = {}
    if os.path.exists(OUT):
        for l in open(OUT):
            l = l.split("#")[0].strip()
            if l:
                keep[l.split()[0]] = l
    rows = []
    paths = []
    for u in t.units:
        paths += glob.glob(os.path.join(ROOT, u.asm_dir, "func_*.s"))
    for p in sorted(paths, key=os.path.basename):
        name = os.path.basename(p)[:-2]
        if not allf and name not in todo:
            continue
        c = counts(p)
        if c and any(c) and name not in keep:
            keep[name] = "%s %s" % (name, " ".join(map(str, c)))
    rows = [keep[k] for k in sorted(keep)]
    with open(OUT, "w", newline="\n") as f:
        f.write("# generated by tools/gen_divs_nops.py: nops retail has before each div.s/sqrt.s, per function\n")
        f.write("\n".join(rows) + "\n")
    print("wrote %s: %d functions" % (OUT, len(rows)))


if __name__ == "__main__":
    main()
