"""The frontbin .text sources: one C file per original source file.

src/frontbin/*.c are listed in link order in tools/src_files.txt. Each file
holds, in address order, the blocks for its functions:

  * decompiled C between /* localdecomp:start func_X */ and
    /* localdecomp:end func_X */ markers (the block's own externs, typedefs
    and prototypes come first, then the function);
  * INCLUDE_ASM / ASM_FUNC / LINKER_REMNANT lines for everything else,
    plus INCLUDE_RODATA and TEXT_PADDING lines that belong to them.

At the top of each file, between the "external declarations" markers, are the
declarations from earlier files that this file's blocks use (generated by
tools/split_text.py and kept up to date by `python tools/split_text.py
--refresh`). Nothing else from other files is visible: each file compiles on
its own, like the original translation units.

This module is shared by the build (tools/build_text.py), tools/try_func.py,
localdecomp and the checks, so they all agree on where a function lives and
what it is compiled with.
"""
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FILES_LIST = os.path.join(ROOT, "tools", "src_files.txt")

EXT_BEGIN = "/* --- declarations from other files (tools/split_text.py --refresh) --- */"
EXT_END = "/* --- end of declarations from other files --- */"


# ---------------------------------------------------------------- file list

def read_file_list(path=FILES_LIST):
    """[(relative path, start address)] in link order."""
    out = []
    for line in open(path):
        line = line.split("#", 1)[0].strip()
        if not line:
            continue
        rel, start = line.split()[:2]
        out.append((rel, int(start, 16)))
    return out


def file_for_address(files, addr):
    """Relative path of the file whose range contains `addr`."""
    best = files[0][0]
    for rel, start in files:
        if addr >= start:
            best = rel
    return best


def read_source(rel, root=ROOT):
    return open(os.path.join(root, rel), errors="replace").read().replace("\r\n", "\n")


# ---------------------------------------------------------------- C scanning

def strip_comments(s):
    out, i, n = [], 0, len(s)
    while i < n:
        c = s[i]
        if c == '"' or c == "'":
            j = i + 1
            while j < n and s[j] != c:
                j += 2 if s[j] == "\\" else 1
            out.append(s[i:j + 1]); i = j + 1
        elif s.startswith("/*", i):
            j = s.find("*/", i + 2); j = n if j < 0 else j + 2
            out.append("\n" * s.count("\n", i, j)); i = j
        elif s.startswith("//", i):
            j = s.find("\n", i); j = n if j < 0 else j
            i = j
        else:
            out.append(c); i += 1
    return "".join(out)


def declaration_statements(chunk):
    """Top-level declarations of a chunk, as a list of statements in order:
    preprocessor lines, typedefs, extern declarations, prototypes, struct /
    union / enum definitions and global register variables. Function bodies,
    top-level asm and anything that allocates storage are left out."""
    s = strip_comments(chunk)
    keep, stmt, depth, i, n = [], [], 0, 0, len(s)
    aggregate = False
    while i < n:
        c = s[i]
        if depth == 0 and not "".join(stmt).strip() and c == "#":
            j = i
            while True:  # preprocessor line with continuations
                k = s.find("\n", j); k = n if k < 0 else k
                if k > 0 and s[k - 1] == "\\":
                    j = k + 1; continue
                break
            keep.append(s[i:k].strip()); i = k + 1; stmt = []; continue
        if c == '"' or c == "'":
            j = i + 1
            while j < n and s[j] != c:
                j += 2 if s[j] == "\\" else 1
            stmt.append(s[i:j + 1]); i = j + 1; continue
        stmt.append(c)
        if c == "{":
            if depth == 0:
                head = "".join(stmt)[:-1]
                aggregate = bool(re.search(r"\b(struct|union|enum)\b[\w\s]*$", head)) or "=" in head
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0 and not aggregate:
                stmt = []  # end of a function definition
        elif c == ";" and depth == 0:
            text = "".join(stmt).strip()
            stmt = []
            if not text:
                pass
            elif text.startswith(("INCLUDE_ASM", "INCLUDE_RODATA", "ASM_FUNC", "LINKER_REMNANT",
                                  "TEXT_PADDING", "__asm__", "asm(", "asm (")):
                pass
            elif text.startswith(("extern", "typedef", "register")) or \
                    re.match(r"^(struct|union|enum)\b[^=]*$", text) or \
                    (re.search(r"\)\s*;?$", text) and "=" not in text and "(" in text):
                keep.append(text)
        i += 1
    return [k for k in keep if k]


def declarations_only(chunk):
    return "\n".join(declaration_statements(chunk))


EXTERN_HINT_RE = re.compile(r'^\s*__asm__\s*\(\s*"\s*\.extern\s[^"]*"\s*\)\s*;', re.M)

_IDENT = re.compile(r"\b[A-Za-z_]\w*\b")
_C_WORDS = set("""auto break case char const continue default do double else enum extern float for goto
if int long register return short signed sizeof static struct switch typedef union unsigned void
volatile while asm __asm__ __volatile__ inline __inline__ __attribute__ define undef ifdef ifndef
endif include line""".split())


def used_names(text):
    """Identifiers a piece of C mentions (strings and comments removed)."""
    s = re.sub(r'"(?:\\.|[^"\\])*"', '""', strip_comments(text))
    return set(_IDENT.findall(s)) - _C_WORDS


def declared_names(stmt):
    """Names a declaration statement introduces (or, for #define/#undef, the macro)."""
    m = re.match(r"#\s*(define|undef)\s+(\w+)", stmt)
    if m:
        return {m.group(2)}
    if stmt.startswith("#"):
        return set()
    names = set()
    body = stmt
    # struct/union/enum tags and enum constants
    for m in re.finditer(r"\b(struct|union|enum)\s+(\w+)\s*\{", body):
        names.add(m.group(2))
    for m in re.finditer(r"\benum\b[^{]*\{([^}]*)\}", body):
        for item in m.group(1).split(","):
            item = item.split("=")[0].strip()
            if item:
                names.add(item)
    # strip aggregate bodies, then read the declarators
    flat = body
    while True:
        new = re.sub(r"\{[^{}]*\}", " ", flat)
        if new == flat:
            break
        flat = new
    flat = flat.rstrip(";")
    flat = re.sub(r"__attribute__\s*\(\(.*?\)\)", " ", flat)
    # a prototype or function pointer: the name right before its parameter list
    for decl in _split_top(flat):
        decl = re.sub(r"=.*", "", decl)
        m = re.search(r"\(\s*\*+\s*(\w+)\s*\)", decl)  # (*name)(...) / (*name)[..]
        if m:
            names.add(m.group(1)); continue
        m = re.search(r"(\w+)\s*\([^()]*(?:\([^()]*\)[^()]*)*\)\s*$", decl)  # name(params)
        if m and m.group(1) not in _C_WORDS:
            names.add(m.group(1)); continue
        decl = re.sub(r"\[[^\]]*\]", " ", decl)
        decl = re.sub(r'__asm__\s*\(\s*"[^"]*"\s*\)', " ", decl)
        ids = [t for t in _IDENT.findall(decl) if t not in _C_WORDS]
        if ids:
            names.add(ids[-1])
    return names


def _split_top(s):
    """Split a declaration on commas that are not inside parentheses."""
    out, depth, cur = [], 0, []
    for c in s:
        if c in "([":
            depth += 1
        elif c in ")]":
            depth -= 1
        if c == "," and depth == 0:
            out.append("".join(cur)); cur = []
        else:
            cur.append(c)
    out.append("".join(cur))
    # the first declarator carries the type; later ones need it to keep their
    # name last, which they already have
    return out


# ---------------------------------------------------------------- blocks

_PAD = r"(?:[ \t\r\n]*^TEXT_PADDING\(\w+\);[^\n]*\n?)?"
BLOCK_RE = re.compile(
    r"(/\* localdecomp:start (func_[0-9A-Fa-f]{8}) \*/.*?/\* localdecomp:end \2 \*/\n?" + _PAD + ")"
    r"|(^(?:INCLUDE_ASM|ASM_FUNC|LINKER_REMNANT)\(\"[^\"]*\",\s*(func_[0-9A-Fa-f]{8})\);[^\n]*\n?"
    r"(?:INCLUDE_RODATA\(\"[^\"]*\",\s*\w+\);[^\n]*\n?)*" + _PAD + ")", re.S | re.M)


def split_chunks(text):
    """[(addr_or_None, start_line, chunk_text)] in order. A chunk is one
    localdecomp block or INCLUDE_ASM-style line (addr = its function) or the
    free-standing text between them (addr = None)."""
    chunks, pos = [], 0
    for m in BLOCK_RE.finditer(text):
        if m.start() > pos:
            chunks.append((None, text.count("\n", 0, pos) + 1, text[pos:m.start()]))
        name = m.group(2) or m.group(4)
        chunks.append((int(name[5:], 16), text.count("\n", 0, m.start()) + 1, m.group(0)))
        pos = m.end()
    if pos < len(text):
        chunks.append((None, text.count("\n", 0, pos) + 1, text[pos:]))
    return chunks


def attach_free_text(chunks):
    """[(addr, line, text)]: free-standing text goes with the next function
    (trailing text with the last one), the way the build has always assigned it."""
    out, pending = [], []
    for addr, line, body in chunks:
        if addr is None:
            pending.append((line, body)); continue
        for pl, pb in pending:
            out.append((addr, pl, pb))
        pending = []
        out.append((addr, line, body))
    last = out[-1][0] if out else 0
    for pl, pb in pending:
        out.append((last, pl, pb))
    return out


def split_file(text):
    """(prelude, external declarations text, [(addr, line, chunk)]) of one
    source file. The prelude is everything before the first block (includes,
    the external declarations section); it belongs to no function."""
    prelude, ext = "", ""
    if EXT_END in text:
        # the prelude ends after the declarations section (and its blank lines);
        # anything after that belongs to the file's first function
        end = text.index(EXT_END) + len(EXT_END)
        while end < len(text) and text[end] == "\n":
            end += 1
        prelude, text_rest = text[:end], text[end:]
        if EXT_BEGIN in prelude:
            ext = prelude.split(EXT_BEGIN, 1)[1].split(EXT_END, 1)[0]
        line0 = prelude.count("\n")
        chunks = [(a, l + line0, b) for a, l, b in split_chunks(text_rest)]
    else:
        chunks = split_chunks(text)
        if chunks and chunks[0][0] is None:
            prelude = chunks[0][2]
            chunks = chunks[1:]
    return prelude, ext, attach_free_text(chunks)


def iter_all(files=None, root=ROOT):
    """(rel, addr, line, chunk) for every chunk of every file, in link order."""
    for rel, _ in (files or read_file_list()):
        _, _, chunks = split_file(read_source(rel, root))
        for addr, line, body in chunks:
            yield rel, addr, line, body


def is_own_chunk(body, name):
    return ("localdecomp:start " + name) in body or bool(
        re.search(r"(?:INCLUDE_ASM|ASM_FUNC|LINKER_REMNANT)\([^)]*\b%s\)" % re.escape(name), body))


def find_function(name, files=None, root=ROOT):
    """(rel path, file text, start offset, end offset) of `name`'s block, or None."""
    files = files or read_file_list()
    addr = int(name[5:], 16)
    order = [file_for_address(files, addr)] + [r for r, _ in files]
    for rel in order:
        text = read_source(rel, root)
        for m in BLOCK_RE.finditer(text):
            if (m.group(2) or m.group(4)) == name:
                return rel, text, m.start(), m.end()
    return None


# ---------------------------------------------------------------- whole-tree helpers

def read_all(root=ROOT, files=None):
    """Every source file concatenated in link order (for searches and counts)."""
    return "\n".join(read_source(rel, root) for rel, _ in (files or read_file_list()))


def transform_all(fn, root=ROOT, files=None, binary=False):
    """Apply fn(text) -> text to every source file; write the ones that change.
    Line endings are kept as they are in each file. Returns the changed paths."""
    changed = []
    for rel, _ in (files or read_file_list()):
        path = os.path.join(root, rel)
        if binary:
            old = open(path, "rb").read()
        else:
            old = open(path, newline="").read()
        new = fn(old)
        if new != old:
            if binary:
                open(path, "wb").write(new)
            else:
                open(path, "w", newline="").write(new)
            changed.append(rel)
    return changed
